In [1]:
import torch
import torch.nn as nn
from collections import OrderedDict
import matplotlib.pyplot as plt

model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 3)),  # first hidden layer with 3 neurons
    ('ReLU', nn.ReLU()),          # relu activation function
    ('output', nn.Linear(3, 2)),  # output layer with 3 neurons
    ('tanh', nn.Tanh())     # sigmoid activation function
]))
print(model1)

data_in1 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in1)

data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)

criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)

# train the model
losses1 = []
for epoch in range(1000):
    # reset the gradients to zero before each forward and backward pass
    optimizer1.zero_grad()    
    outputs1 = model1(data_in1) # forward pass
    loss1 = criterion1(outputs1, data_target1) # calculate loss
    loss1.backward()          # backward pass
    optimizer1.step()         # update weights
    losses1.append(loss1.item())
    predicted_classes1 = (outputs1.round() == data_target1)
    accuracy1 = predicted_classes1.sum().item() / len(data_target1)
    if accuracy1 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break

# visualize the resuts
print(outputs1)
predicted = torch.round(outputs1)
correct = (predicted == data_target1).sum()
total = data_target1.size(0)
accuracy = correct / total
print(f'Model Accuracy: {accuracy}%') 

# print model wights
print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)


Sequential(
  (hidden): Linear(in_features=2, out_features=3, bias=True)
  (ReLU): ReLU()
  (output): Linear(in_features=3, out_features=2, bias=True)
  (tanh): Tanh()
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Model 1 reached 100% accuracy at epoch 2
tensor([[ 0.4958, -0.1303],
        [ 0.6364, -0.3876],
        [ 0.5722, -0.1275],
        [ 0.7356, -0.4573]], grad_fn=<TanhBackward0>)
Model Accuracy: 1.0%
Model weights:
hidden.weight tensor([[ 0.0274,  0.0272],
        [-0.3173,  0.1806],
        [ 0.3455,  0.5465]])
hidden.bias tensor([ 0.4441,  0.3299, -0.2096])
output.weight tensor([[ 0.3619, -0.0030,  0.4864],
        [ 0.1176, -0.3293, -0.5019]])
output.bias tensor([0.3492, 0.0247])
